---
#NOTE: This playbook is not idempotent

- name: Install firewalld
  ansible.builtin.dnf:
    name: firewalld
    state: present

- name: Ensure firewalld is running
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Disable all repositories
  ansible.builtin.command: subscription-manager repos --disable "*"

- name: Enable specific repositories
  ansible.builtin.command: >
    subscription-manager repos
    --enable=rhel-8-for-x86_64-baseos-rpms
    --enable=rhel-8-for-x86_64-appstream-rpms
    --enable=satellite-6.15-for-rhel-8-x86_64-rpms
    --enable=satellite-maintenance-6.15-for-rhel-8-x86_64-rpms

- name: Open ports for Satellite Client
  ansible.builtin.command: >
    firewall-cmd \
    --add-port="5647/tcp" \
    --add-port="8000/tcp" \
    --add-port="9090/tcp"

- name: Allow access to services on Satellite Server
  ansible.builtin.command: >
    firewall-cmd \
    --add-service=dns \
    --add-service=dhcp \
    --add-service=tftp \
    --add-service=http \
    --add-service=https \
    --add-service=puppetmaster

- name: Make firewall changes persistent
  ansible.builtin.command: firewall-cmd --runtime-to-permanent

- name: Set hostname
  ansible.builtin.command: hostnamectl set-hostname satellite

- name: Enable Satellite module
  ansible.builtin.command: dnf module enable -y satellite:el8

- name: Update all packages
  ansible.builtin.command: dnf update -y

- name: Install Satellite
  ansible.builtin.command: dnf install -y satellite

- name: Install Chrony
  ansible.builtin.command: dnf install -y chrony

- name: Enable and start Chrony
  ansible.builtin.command: systemctl enable --now chronyd

- name: Install sos package via satellite-maintain
  ansible.builtin.command: satellite-maintain packages install sos

- name: Run Satellite installer
  ansible.builtin.command: >
    satellite-installer --scenario satellite
    --foreman-initial-organization "Demo_Organization"
    --foreman-initial-location "Raleigh"
    --foreman-initial-admin-username admin
    --foreman-initial-admin-password password123
